# Generated by Django 3.2.3 on 2022-10-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSITUweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
